version: '3'
services:
  app:
    build: .
    ports:
      - "8004:8004"
    volumes:
      - .:/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: otp_mongo
    ports:
      - "8001:27017"
    volumes:
      - ./mongo-data:/data/db