name: shopping_mart
description: A Flutter app for shopping mart
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  dio: ^5.4.0
  fluttertoast: ^8.2.2
  shared_preferences: ^2.2.2
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true